# Generated by Django 5.2.11 on 2026-03-05 04:43

import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Profile photo (JPG, PNG). Max 5MB.', null=True, upload_to=profiles.models.profile_image_path),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='github',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='linkedin',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='location',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='website',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterModelTable(
            name='personalinfo',
            table=None,
        ),
    ]
